version: "2"
services:
  db:
    image: "mysql:5.7"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: game_db
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
        - '3306:3306'
    expose:
      - "3306"
    volumes:
      - db:/var/run/mysqld
    logging:
      driver: none
    ports:
      - "33061:3306"
  web:
    build: ./game-server
    command: bundle exec rails s -p 3000 -e development -b '0.0.0.0'
    environment:
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: game_db
      DB_PORT: 3306
      DB_HOST: db
      RAILS_ENV: development
      RAILS_MAX_THREADS: 5
      JWT_SECRET: 6lx0ZQiUA0AZGw9wp0lUNYRsUIAOyjLU
      ADMIN_NAME: admin
      ADMIN_SURNAME: admin
      ADMIN_PASSWORD: admin
      BUNDLE_PATH: /bundle
    volumes:
      - ./game-server/:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db

  client:
    build:
      context: ./game-client
      dockerfile: Dockerfile
    volumes:
      - './game-client:/usr/src/app'
      - '/usr/src/app/node_modules'

    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: /usr/src/app/entrypoint.sh
    
  adminer:
      image: adminer:latest
      environment: 
          ADMINER_DEFAULT_SERVER: db
      ports: 
        - 8080:8080      

volumes: 
  db:
